# Site settings
title: A blog about lorem ipsum dolor sit amet
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Nikos Savvidis
user_description: Personal Website 
user_title: Software Engineer
email: ncs@ncs.cy
twitter_username: ncs-one
github_username:  ncs-one
linkedin_username: nsavvidis

exclude: ['package.json', 'src' , 'node_modules']
